document.body.className = 'v1';
const content=document.getElementById('content');
content.innerHTML="<section id=\"about\" class=\"scroll-section profile-panel\" aria-label=\"About Hanshal Goyal\"><figure class=\"profile-portrait\"><img src=\"assets/portrait-closeup.png\" alt=\"Pixelated portrait of Hanshal Goyal\" width=\"160\" height=\"180\"></figure><div class=\"profile-bio\"><p>I\u2019m a Member of Technical Staff at <a href=\"https://www.mantic.com/\" target=\"_blank\" rel=\"noopener noreferrer\">Mantic</a> where I work on post-training. We are on a mission to solve forecasting and radically improve human decision making.</p><p>I briefly worked on sequential Bayesian experimental design research at <a href=\"https://oatml.cs.ox.ac.uk/\" target=\"_blank\" rel=\"noopener noreferrer\">OATML</a> during my visiting student year at <a href=\"https://www.ox.ac.uk/\" target=\"_blank\" rel=\"noopener noreferrer\">Oxford</a>. I am currently on a leave of absence from <a href=\"https://www.brown.edu/\" target=\"_blank\" rel=\"noopener noreferrer\">Brown</a> where I study Engineering Physics.</p><p>I\u2019m interested in reinforcement learning, Bayesian inference, decision making under uncertainty, and AI for science.</p><p>I grew up in Melbourne, Australia and am currently based in London, UK. I love travelling, music, cricket and learning more about physics, philosophy, history and politics.</p></div><ul class=\"profile-links\" aria-label=\"Contact and profile\"><li><a href=\"mailto:hanshalgoyal@gmail.com\">hanshalgoyal [at] gmail [dot] com</a></li><li><a href=\"https://x.com/hanshalgoyal\" target=\"_blank\" rel=\"noopener noreferrer\">X \u00b7 @hanshalgoyal</a></li><li><a href=\"https://www.linkedin.com/in/hanshal-goyal-54bba8262/\" target=\"_blank\" rel=\"noopener noreferrer\">LinkedIn</a></li></ul></section><section id=\"publications\" class=\"scroll-section\" aria-labelledby=\"publications-title\"><div class=\"section-banner\"><h2 class=\"page-title\" id=\"publications-title\">Publications</h2></div><article class=\"publication\"><div class=\"paper-meta\"><span>2026</span><span>JOURNAL OF INSTRUMENTATION</span></div><h3><a href=\"https://doi.org/10.1088/1748-0221/21/08/C08015\" target=\"_blank\" rel=\"noopener noreferrer\">Machine learning-based reconstruction for resistive silicon sensors <span aria-hidden=\"true\">\u2197</span></a></h3><p class=\"paper-authors\">A. Aoki, G. Barone, L. Diehl, G. Giacomini, E. L. Gkougkousis, <strong>H. Goyal</strong>, et al.</p></article></section>";
document.title='Hanshal Goyal - Portfolio';
const ids=['about','publications'];
function activate(id){document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});}
let scheduled=false;
function updateNavigation(){scheduled=false;let active='about';for(const section of document.querySelectorAll('.scroll-section'))if(section.getBoundingClientRect().top<=150)active=section.id;if(innerHeight+scrollY>=document.documentElement.scrollHeight-8)active='publications';activate(active);}
addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateNavigation)}},{passive:true});
addEventListener('resize',updateNavigation);
activate(ids.includes(location.hash.slice(1))?location.hash.slice(1):'about');
if(ids.includes(location.hash.slice(1)))requestAnimationFrame(()=>document.getElementById(location.hash.slice(1)).scrollIntoView());
